name: Deploy Supabase Functions

on:
  push:
    branches: [ main ]
    paths:
      - 'supabase/functions/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Supabase CLI
      uses: supabase/setup-cli@v1
      with:
        version: latest

    - name: Deploy Functions
      run: |
        supabase functions deploy ai-chat --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
        supabase functions deploy propose-diff --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
        supabase functions deploy index-repo --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

    - name: Set secrets
      run: |
        supabase secrets set OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
        supabase secrets set ANTHROPIC_API_KEY="${{ secrets.ANTHROPIC_API_KEY }}" --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
        supabase secrets set GOOGLE_AI_API_KEY="${{ secrets.GOOGLE_AI_API_KEY }}" --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
      env:
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}