name: 'Web App CI/CD'

on:
  push:
    branches: [ main, develop ]
    paths: [ 'web-app/**', '.github/workflows/web-app-ci.yml' ]
  pull_request:
    branches: [ main ]
    paths: [ 'web-app/**' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    name: 'Lint & Test Web App'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web-app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './web-app/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run type checking
        run: npm run type-check

      - name: Run tests
        run: npm run test

      - name: Build for production
        run: npm run build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

  # deploy-preview:
  #   name: 'Deploy Preview'
  #   runs-on: ubuntu-latest
  #   needs: lint-and-test
  #   if: github.event_name == 'pull_request'
  #   defaults:
  #     run:
  #       working-directory: ./web-app

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Deploy to Vercel Preview
  #       uses: amondnet/vercel-action@v25
  #       with:
  #         vercel-token: ${{ secrets.VERCEL_TOKEN }}
  #         vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
  #         vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
  #         working-directory: ./web-app
  #         scope: ${{ secrets.VERCEL_ORG_ID }}

  # deploy-production:
  #   name: 'Deploy to Production'
  #   runs-on: ubuntu-latest
  #   needs: lint-and-test
  #   if: github.ref == 'refs/heads/main'
  #   defaults:
  #     run:
  #       working-directory: ./web-app

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Deploy to Vercel Production
  #       uses: amondnet/vercel-action@v25
  #       with:
  #         vercel-token: ${{ secrets.VERCEL_TOKEN }}
  #         vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
  #         vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
  #         vercel-args: '--prod'
  #         working-directory: ./web-app
  #         scope: ${{ secrets.VERCEL_ORG_ID }}

  #     - name: Update deployment status
  #       if: success()
  #       run: |
  #         echo "🚀 Web app deployed successfully to production!"
  #         echo "🌐 URL: https://branchcode.vercel.app"